# Site
repository: sproogen/resume-theme
# favicon: Directory of your favic (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2
locale: "ko-KR"
# Personal info
name: heejin Shin
title: ì‹ ì… ê°œë°œì ì‹ í¬ì§„ì…ë‹ˆë‹¤. 
title_separator: "|"
# email: heejinshin02@gmail.com
# email_title: Email (Email title override)
# phone: 010-9550-2413
# phone_title: Phone (Phone title override)
# website: https://github.com/heejinshin
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false


github_username:  heejinshin
stackoverflow_username: "19754540"
instagram_username: tam_anama

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.png
about_content: | # this will include new lines to allow paragraphs
     í˜¼ìì„œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ë©° ë§ˆì£¼í•œ ì˜¤ë¥˜ë“¤ì„ í•´ê²°í•˜ê¸° ìœ„í•´ ì•½ ë‘ ë‹¬ê°„ ìŠ¤íƒì˜¤ë²„í”Œë¡œë¥¼ í†µí•œ 70ì—¬ê°œì˜ ì§ˆë¬¸ê³¼ êµ¬ê¸€ë§ì€ ë¬¼ë¡  ì„ ë°° ê°œë°œìë¶„ë“¤ê»˜ ì¡°ì–¸ì„ ì–»ëŠ” ë“± ì§‘ìš”í•œ ë…¸ë ¥ ëì— ê¸°ëŠ¥ êµ¬í˜„ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤. ì´ì²˜ëŸ¼ ì €ëŠ” ë¬¸ì œ í•´ê²°ì„ ìœ„í•´ ëê¹Œì§€ í¬ê¸°í•˜ì§€ ì•Šê³  ë‹¤ì–‘í•œ ë°©ë²•ì„ ì‹œë„í•˜ê³  ê²°êµ­ì—ëŠ” í•´ê²°í•´ë‚´ê³ ì•¼ ë§ˆëŠ” ì„±í–¥ì˜ ì‹ ì… ê°œë°œìì…ë‹ˆë‹¤. ì•ìœ¼ë¡œë„ ì…ì‚¬ í›„ ì˜ë¯¸ ìˆëŠ” ê²°ê³¼ë¬¼ì„ ë§Œë“¤ì–´ ë‚´ëŠ” ê°œë°œìê°€ ë˜ê² ìŠµë‹ˆë‹¤.
      - ğŸ’ğŸ»â€â™€ï¸ Name: ì‹  í¬ ì§„ 
      - ğŸ  Adress: ì„œìš¸ì‹œ ìš©ì‚°êµ¬ 
      - ğŸ“± Contact: 010-9550-2413 
      - ğŸ“¨ Email: heejinshin02@gmail.com
 

content:
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ì‚¬ìš©ê°€ëŠ¥í•œ ê¸°ìˆ  ìŠ¤íƒ
#         link: github.com/heejinshin/My-Data
      
#         additional_links:
#           - title: sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: sproogen.github.io/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             # icon: fab fa-github
#             # url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         quote: >
#           ì™¸ë¶€ apiì™€ ë‹¤ì–‘í•œ í”ŒëŸ¬í„° UIë¥¼ í™œìš©í•œ ì•± í”„ë¡œì íŠ¸ì…ë‹ˆë‹¤. 
        description: | # this will include new lines to allow paragraphs
          ì£¼ë¡œ ì‚¬ìš©í•˜ëŠ” ê¸°ìˆ  ìˆœìœ¼ë¡œ ê¸°ì¬í•˜ì˜€ìŠµë‹ˆë‹¤. 
           - Flutter: UIë¥¼ êµ¬í˜„í•˜ëŠ”ë° ì£¼ë¡œ ì“°ì´ëŠ” ìœ„ì ¯ë“¤ì„ ììœ ìì¬ë¡œ í™œìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. getXë¥¼ í†µí•œ ìƒíƒœê´€ë¦¬ë¥¼ ì´í•´í•˜ë©° í™œìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ë¦¬íŒ©í† ë§ì´ë‚˜ ë„¤ì´í‹°ë¸Œ ì—°ê²°ì„ ìœ„í•œ êµ¬í˜„ì€ ì•„ì§ ì–´ë µìŠµë‹ˆë‹¤.
           - Docker: ë„ì»¤ë¥¼ í™œìš©í•˜ì—¬ ì›¹ ì„œë²„ í˜¹ì€ ë°ì´í„°ë² ì´ìŠ¤ì— ì§„ì…ê³¼ ê°™ì€ ê¸°ë³¸ì ì¸ ì„œë²„ í†µì‹  ì‘ì—…ì„ í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
           - Postgresql: Postgres ìŠ¤í‚¤ë§ˆì˜ ì„¤ê³„ì™€ ê¸°ë³¸ SQLë¬¸ì„ í™œìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
           - Gin: Goì–¸ì–´ë¡œ ì›¹ http ì„œë²„ ê¸°ë³¸ í†µì‹  ë¡œì§ êµ¬í˜„ì„ í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
           - Django, ë¶€íŠ¸ìŠ¤íŠ¸ë©: Pythonìœ¼ë¡œ ì›¹ê°œë°œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰ ë° ê°œë°œí•œ ê²½í—˜ì´ ìˆìŠµë‹ˆë‹¤. 
           - Selenium: Pythonìœ¼ë¡œ ë„¤ì´ë²„ ì‡¼í•‘ ì›¹ í¬ë¡¤ë§ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤. 
           - Arduino / RasberryPi: IoT ì‚¬ë¬¼ì¸í„°ë„· ê°œë°œ ì–‘ì„±ê³¼ì • êµìœ¡ì„ í†µí•´ ê´€ë ¨ í”„ë¡œì íŠ¸ë¥¼ ìˆ˜í–‰í•˜ì˜€ìŠµë‹ˆë‹¤. 
          

        
          
  - title: 
    layout: list
    content:
      - layout: left
        title: ê´€ë ¨êµìœ¡ ì´ìˆ˜ì‚¬í•­ 
#         sub_title: 
         
#         caption: 21.06 - 21.09
#         quote: >
 
        description: | # this will include new lines to allow paragraphs
          - ë©€í‹°ìº í¼ìŠ¤ IOT ì‚¬ë¬¼ì¸í„°ë„· ê°œë°œì ì–‘ì„±ê³¼ì • (21.06 - 21.09, ì¤‘ë„ í•˜ì°¨)
          - KISA ë¸”ë¡ì²´ì¸ í•€í…Œí¬ ì•„ì¹´ë°ë¯¸ (22.09)
          - ì½”ë©˜í†  GoLang ì‹¤ë¬´ PT ì• í”Œë¦¬ì¼€ì´ì…˜ ê°œë°œ (23.01)
               - íŒŒì´ì¬, Djangoë¡œ ì›¹ê°œë°œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰, signup, signinê¸°ëŠ¥ ë° ê²Œì‹œíŒ ê¸°ëŠ¥ì„ ê°œë°œí•˜ì˜€ìŠµë‹ˆë‹¤. 
               - ê°€ë‚˜ìŠˆë¥¼ í™œìš©í•˜ì—¬ ì´ë”ë¦¬ì›€ ë„¤íŠ¸ì›Œí¬ë¥¼ í†µí•œ í† í° ë°œí–‰, NFT ë°œí–‰ ë° ì§€ê°‘ ì—°ê²° ê¸°ëŠ¥ì„ êµ¬í˜„í•˜ì˜€ìŠµë‹ˆë‹¤.
               - gin í”„ë ˆì„ì›Œí¬ì™€ Docker ë¥¼ í™œìš©í•˜ì—¬ CRUD êµ¬í˜„, Postmanì„ í™œìš©í•œ ì›¹ ì„œë²„ restapi ê°œë°œì„ í•˜ì˜€ìŠµë‹ˆë‹¤. 
               
  - title: 
    layout: list
    content:
      - layout: left
        title: ì—…ë¬´ ê²½ë ¥ì‚¬í•­ 
        sub_title: 
         
         
#         caption: ì´ë¬´ / ì„¸ë¬´ / ë…¸ë¬´ 
#         quote: > 
           
        description: | # this will include new lines to allow paragraphs
         
          ìŠ¤íƒ€íŠ¸ì—…ì—ì„œ ì•½ 9ê°œì›”ê°„ ê·¼ë¬´í•œ ê²½í—˜ì´ ìˆìŠµë‹ˆë‹¤. ê²½ì˜ì§€ì› ë¶€ì„œì˜ ì „ë°˜ì— ê±¸ì³ ì•½ 2ë…„ê°„ ê·¼ë¬´í•œ ê²½í—˜ìœ¼ë¡œ íšŒì‚¬ ë‚´/ì™¸ë¶€ì—ì„œ í™œë°œí•œ ì»¤ë®¤ë‹ˆì¼€ì´ì…˜ì„ í•˜ë©° ì—…ë¬´ë¥¼ ìˆ˜í–‰í•˜ëŠ” ëŠ¥ë ¥ì„ ê°–ì¶”ì—ˆìŠµë‹ˆë‹¤. 
           - (ì£¼)ì¡°ì„ ë‚´í™”ì´ì—”ì§€_êµ¬ë§¤(17.03 - 18.04)
           - (ì£¼)ì½”ìŠ¤ëª¨ìŠ¤ì´í™íŠ¸_ê²½ì˜ì§€ì›(21.09 - 22.05)



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

